import SwiftData

/// Single source of truth for the on-disk **SwiftData** schema (app container + Sovereign restore sidecar).
enum LibrarySwiftDataSchema {
    /// Stable fingerprint for store-recovery messaging when the schema grows.
    static var schemaFingerprint: String {
        "v2026-06-24-sovereign-profile-privacy"
    }

    static func makeSchema() -> Schema {
        Schema([
            Item.self,
            Receipt.self,
            ReceiptImage.self,
            ReceiptLineItem.self,
            WorkSession.self,
            WorkRecord.self,
            BankTransaction.self,
            LedgerBankAccount.self,
            ReceiptReferenceLink.self,
            ProductionProject.self,
            BusinessEntity.self,
            PreliminaryBusinessEntity.self,
            EquipmentAsset.self,
            ProductionKitCheckout.self,
            ProductionContact.self,
            CabinetFolder.self,
            ArcticVaultFolder.self,
            MerchantFilingRule.self,
            SovereignAuditLogEntry.self,
            SovereignProfile.self,
            LaborAgreement.self,
            ShowLaborPositionRate.self,
            CrewTimecardDay.self,
            RecordTombstone.self,
            ProductionProjectDeletionTombstone.self,
            MediaAsset.self,
            LyricSegment.self,
            MetadataCard.self,
            HistoricalKnowledgeNode.self,
            MaatDeclaration.self,
            MediaProductionBeat.self,
            MasterUserIdentity.self,
            CraftMenuItem.self,
            ShuttleDeliveryOrder.self,
            ProductionApprovalRule.self,
            ProductionPurchaseOrder.self,
            CateringSupplyItem.self,
            RunRequestTicket.self,
            TransportDispatchTicket.self,
            VenueCheckoutSession.self,
            CraftMicroPurchase.self,
            CrewFeedbackTicket.self,
            ProductionCallSheetDay.self,
            TransportVehicleRun.self,
            CrossVentureOrderTicket.self,
            CrewCommsNotice.self,
            MedicTreatmentIncident.self,
            MedicKitSupplyItem.self,
            MedicCoverageInterval.self,
            LSPLocationTask.self,
            SecurityAccessLog.self,
            ExpertConsultantProfile.self,
            ConsultationTimecard.self,
            InvitationNode.self,
            ExpertDiagnosticSubmission.self,
            DepartmentForumPost.self,
            DailyTimeReportEntry.self,
            FrictionEventLog.self,
            ScriptSceneBreakdown.self,
            RFIDAssetItem.self,
            TrailerOperationalUnit.self,
            WorkerPayrollWeekStatus.self,
            TemporalRoleGrant.self,
            CreativeFirstLookSnapshot.self,
            ProductionUnitCrisisNode.self,
            SpatialBeaconAsset.self,
            SpatialCrewPosition.self,
            LocationsEquipmentAsset.self,
            LocationsTruckManifest.self,
            LocationsGreenZone.self,
            ExecutiveLogisticsSnapshot.self,
            RTLSReceiverNode.self,
            ActiveTransitToken.self,
            // New Horizons — Estate Technical Database Structures
            TelemetryReading.self,
            VerticalFarmingLog.self,
            CuratedAsset.self,
            CuratedAssetDocument.self,
            CuratedAssetProvenanceEvent.self,
        ])
    }
}
