name: macOS Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build (macOS)
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Resolve Swift packages (if any)
        run: xcodebuild -resolvePackageDependencies -project "RatioVita.xcodeproj"
      - name: Build (macOS target)
        run: xcodebuild -project "RatioVita.xcodeproj" -scheme "RatioVita" -destination "platform=macOS" build | xcpretty

  test:
    name: Test (macOS)
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Run tests (macOS)
        run: xcodebuild -project "RatioVita.xcodeproj" -scheme "RatioVita" -destination "platform=macOS" -enableCodeCoverage YES test | xcpretty
